{% set data = load_setup_py_data() %}

package:
  name: pyvcf
  version: {{ data.version }}

source:
  path: ../../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7

about:
  home: {{ data.url }}
  license: {{ data.license }}
  summary: {{ data.description }}
